// ==========================================
// Service Types
// ==========================================
// This file re-exports from centralized types for backward compatibility
// New code should import from '@/types' directly
// ==========================================

// Re-export all types from centralized location
export type {
  User,
  UserRole,
  UserStatus,
  AuthUser,
  LoginCredentials,
  RegisterData,
  LoginResponse,
  AuthTokens,
  ApiResponse,
  ApiError,
  Competition,
  CompetitionStatus,
  CompetitionDisplayStatus,
  CompetitionCategory,
  CompetitionTimeline,
  CompetitionJudge,
  MainCompetition,
  CompetitionFormData,
  Team,
  TeamStatus,
  PaymentStatus,
  TeamMember,
  TeamMemberRole,
  Stage,
  StageStatus,
  Task,
  Submission,
  SubmissionStatus,
  JudgeAssignment,
  JudgeAssignmentStatus,
  JudgeScore,
  Notification,
  Announcement,
  AuditLog,
  PortfolioItem,
  PortfolioFormData,
  NewsItem,
  NewsFormData,
  FeaturedEvent,
  FeaturedEventFormData,
  PaginationParams,
  PortfolioQueryParams,
  NewsQueryParams,
  CompetitionQueryParams,
  UploadResponse,
  RegistrationFormData,
  CompetitionRegistration,
} from '@/types';